# Generated by Django 2.1.3 on 2018-12-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181204_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='qeustion',
            new_name='question',
        ),
    ]
